// examples/vue-app/src/components/FlourishComponent.vue
<template>
    <div class="flourish-container" ref="flourishContainer"></div>
  </template>
  
  <script>
  import { Flourish } from 'flourish-sdk-web';
  
  export default {
    name: 'FlourishComponent',
    props: {
      token: {
        type: String,
        required: true
      },
      language: {
        type: String,
        default: 'en'
      },
      environment: {
        type: String,
        required: true
      }
    },
    mounted() {
      // Initialize the Flourish SDK and append the iframe to the container
      const flourishApp = Flourish(this.token, this.language, this.environment, this.handleGenericEvent);
      this.$refs.flourishContainer.appendChild(flourishApp);
    },
    methods: {
      handleGenericEvent(data) {
        console.log('Generic event received in Vue Example:', data);
      }
    }
  };
  </script>
  
  <style scoped>
  .flourish-container {
    width: 100%;
    height: 100vh; /* Full viewport height */
  }
  </style>

// examples/angular-app/src/app/flourish/flourish.component.ts
import { Component, ElementRef, Input, OnInit } from '@angular/core';
import { Flourish } from 'flourish-sdk-web';

@Component({
  selector: 'app-flourish',
  standalone: true,
  templateUrl: './flourish.component.html',
  styleUrl: './flourish.component.css'
})
export class FlourishComponent implements OnInit {

  @Input() token!: string;
  @Input() language: string = 'en';
  @Input() environment!: string;

  constructor(private elementRef: ElementRef) {}

  ngOnInit(): void {
    // Initialize the Flourish SDK and append the iframe to the container
    const flourishIframe = Flourish(this.token, this.language, this.environment, this.handleGenericEvent);
    this.elementRef.nativeElement.querySelector('.flourish-container').appendChild(flourishIframe);
  }

  handleGenericEvent(data: any): void {
    console.log('Generic event received in Angular Example:', data);
  }

}
